### PR TITLE
zsdcc - update to 4.5.0 r15248

### LINKED ISSUE #2635: zsdcc - Internal Error in file 'SDCCopt.c' line number '312'
When compiling by test code it seems to break the optimizer casting int16_t to float:

```
#include <stdint.h>

uint8_t IntNorms[2][04] ={ {0x1F, 0x00, 0x3E, 0x1F},
                           {0x9F, 0x12, 0x37, 0x10},  };

float normalsf[13][3];


void main(void)
{
    uint8_t i = 0;
    while (i < 2)
    {
        uint8_t value8x = IntNorms[i][0];
        int16_t value16x = (int16_t)IntNorms[i][0];
        normalsf[i][0] = (float)value16x;
        ++i;
    }
    while (1==1);
}     
```
Compiled on windows cmd: 
zcc +zxn -c -vn -compiler=sccz80 -clib=sdcc_iy --math32 -SO2 --max-allocs-per-node3000 CodeTest.c
Gives CodeTest.c:20: error 9: FATAL Compiler Internal Error in file 'SDCCopt.c' line number '312' : 0
If I change the while loop to cast the uint8_t to float 
"normalsf[i][0] = (float)value8x;"
that compiles fine
and if I change the loop to

    while (i < 2)
    {
        uint8_t value8x = IntNorms[i][0];
        int16_t value16x = 2;
        normalsf[i][0] = (float)value16x;
        ++i;
    }
that compiles fine
but this fails:
    while (i < 2)
    {
        uint8_t value8x = 2;
        int16_t value16x = (int16_t)IntNorms[i][0];
        normalsf[i][0] = (float)value16x;
        ++i;
    }
    while (1==1);

I think its an issue with casting int16_t to float tripping up the optimiser. It looks to have happened at least in the nightly builds since around 10-Sept according to when I last downloaded a nightly build. Also happens with last nights.

Running under Win10 pro

### LINKED ISSUE #2658: Please test SDCC 4.5.0 RC1
Since z88dk uses SDCC, and SDCC is working on a SDCC 4.5.0 release (there is an RC1 since about a week ago), it probably would be good to test, and report (here or at the sdcc-user list) how bad/well SDCC 4.5.0 RC1 works for z88dk.

### PR DESCRIPTION
**Pull request by feilipu**
A patch to v4.5.0-rc1 (r15212) for zsdcc, for testing.

Will do a final version once v4.5.0 is released.

Closes #2658
Closes #2635

### CODE REVIEW

**Comment by feilipu** [comment]
The 4.5.0 Release has been completed at r15248. Updated the patch appropriately.
Ready to merge when the patched source tar file is available and the build tests pass.

**Comment by feilipu** [comment]
@suborb could you do the honours with the source tarball for the nightly, when you get a chance, please?

And poke the CI elves too.

**Comment by suborb** [comment]
Ok, all sorted, merging.
