### ISSUE TITLE
[bug][windows] Z88DK (Windows) no longer works since July 24th

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2066]
The latest Windows snapshot (z88dk-win32-20220809-35b9fafdb-19812) no longer works.
I get an error about not being able to find iteratordeEv.

This problem is trivially reproduced by running the "zcc" on any C file, for example:
```
zcc +ace test.c
```

Remark: Version from the 31st of May, 2022 does not have this issue.

![image](https://user-images.githubusercontent.com/29057615/183772875-98bb9596-16f4-49d0-9ff8-45e37a09be9e.png)

**Comment by pauloscustodio** [comment]
Do you have g++ installed in Cygwin? The referred entry point is from the C++ std::filesystem library.

**Comment by pauloscustodio** [comment]
You need the following Cygwin packages:
gcc-g++ bison flex libxml2-devel libiconv-devel zlib-devel liblzma-devel wget unzip dos2unix autoconf automake libtool ragel perl perl-Regexp-Common perl-Test-Harness perl-Text-Diff perl-YAML-Tiny perl-Module-Build perl-List-MoreUtils perl-Params-Util Perl-B-COW Perl-Clone

**Comment by Fabrizio-Caruso** [comment]
@pauloscustodio this is not a Cygwin issue. I get the same error under Windows if I use the the standard Windows command line.

**Comment by Fabrizio-Caruso** [comment]
@pauloscustodio This is an issue about the Windows snapshot, built for Windows. The problem appears under Windows without Cygwin and also appears under Cygwin. Previous versions still work correctly under Windows.

**Comment by Fabrizio-Caruso** [comment]
@pauloscustodio I am removing Cygwin from the description of the problem. I have double checked this on a different computer. The Windows version of Z88DK is no longer usable.

**Comment by pauloscustodio** [comment]
@suborb, maybe we need to tell gcc in the build snapshot script to link staticaly? See https://stackoverflow.com/questions/6578484/telling-gcc-directly-to-link-a-library-statically

**Comment by suborb** [comment]
There’s meant to be a c++ dll in the kit.

**Comment by pauloscustodio** [comment]
Depends.exe outputs: 
```
Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Warning: At least one delay-load dependency module was not found.
```

On LIBSTDC++-6.DLL all the std::filesystem functions are undefined. std::filesystem was introduced in C++17. Maybe we need a newer version of LIBSTDC++-6.DLL?

**Comment by pauloscustodio** [comment]
I've checked the released version 2.2, and it is OK. The error was introduced in commit 8a0f54f8a3e4ee06816a0c43ad9dd865ad3f80be, just after the release of 2.2, when I ported the command line parsing of z80asm to C++, and starting using std::filesystem from C++17.

**Comment by Fabrizio-Caruso** [comment]
Once this issue has been solved, would it be possible to have a sort of automatic test of the dependencies in the continuous integration?

**Comment by suborb** [comment]
@pauloscustodio I think it needs a static link to the fs library, all that's on the system is the following (no libstdc++7 on the machine):

```
./gcc/x86_64-w64-mingw32/9.3-posix/libstdc++fs.a
./gcc/x86_64-w64-mingw32/9.3-posix/libstdc++-6.dll
./gcc/x86_64-w64-mingw32/9.3-posix/libstdc++.dll.a
./gcc/x86_64-w64-mingw32/9.3-posix/libstdc++.dll.a-gdb.py
./gcc/x86_64-w64-mingw32/9.3-posix/libstdc++.a
./gcc/x86_64-w64-mingw32/9.3-win32/libstdc++fs.a
./gcc/x86_64-w64-mingw32/9.3-win32/libstdc++-6.dll
./gcc/x86_64-w64-mingw32/9.3-win32/libstdc++.dll.a
./gcc/x86_64-w64-mingw32/9.3-win32/libstdc++.dll.a-gdb.py
./gcc/x86_64-w64-mingw32/9.3-win32/libstdc++.a
./gcc/i686-w64-mingw32/9.3-posix/libstdc++fs.a
./gcc/i686-w64-mingw32/9.3-posix/libstdc++-6.dll
./gcc/i686-w64-mingw32/9.3-posix/libstdc++.dll.a
./gcc/i686-w64-mingw32/9.3-posix/libstdc++.dll.a-gdb.py
./gcc/i686-w64-mingw32/9.3-posix/libstdc++.a
./gcc/i686-w64-mingw32/9.3-win32/libstdc++fs.a
./gcc/i686-w64-mingw32/9.3-win32/libstdc++-6.dll
./gcc/i686-w64-mingw32/9.3-win32/libstdc++.dll.a
./gcc/i686-w64-mingw32/9.3-win32/libstdc++.dll.a-gdb.py
./gcc/i686-w64-mingw32/9.3-win32/libstdc++.a
```

**Comment by pauloscustodio** [comment]
Added fix to llink libc and libc++ statically when cross-compiling so that we can use C++17 features on older systems.
Also added cron job to github workflows to test the win32 daily build at 6 AM every day.

Let's see if tomorrow the problem is solved.

**Comment by Fabrizio-Caruso** [comment]
Thanks @pauloscustodio and @suborb ! The issue is fixed for me.

**Comment by pauloscustodio** [comment]
z88dk-win32-20220824-7db629d7e-19857\z88dk\bin\z88dk-z80asm.exe fails with error:
![image](https://user-images.githubusercontent.com/70773/186397866-1505613c-9dd6-45e0-a42f-8971c72d2ba3.png)

**Comment by pauloscustodio** [comment]
Solved by linking libc and libc++ statically (https://github.com/z88dk/z88dk/commit/a30b0b4f849a4244c5da9dd784808b761406e9d3)

**Comment by pauloscustodio** [comment]
I have removed the static libraries needed to include std::experimental::filesystem, and included boost::filesystem instead.
To link with Boost, ```-lboostfilesystem-mt``` is needed in ```msys2```, I don't know if the same library name is used in other platforms. If yes, ```src/z80asm/build_ldflags.pl``` may need some tweaking

**Comment by suborb** [comment]
@pauloscustodio I think you may have reintroduced the original problem?

I thought the static link on windows was there so that the windows binary (built from nightly) could run on older mingw installations?

**Comment by pauloscustodio** [comment]
I have missed this message and saw in your changes in the build script; they seem fine. Let's wait for tonight's nightly

**Comment by suborb** [comment]
Sorry, I didn't meant to check that in!

I think we now solve for 1,3,4 case 2 is solved for Windows, but not for macOS.

For macOS, and nightly (i.e. CROSS=1) I think we need to force using boost regardless of the autodetection (this PR https://github.com/z88dk/z88dk/pull/2205 but adjusted to the perl script)
