### ISSUE TITLE
[snap][bug?] Random errors when compiling the same code in parallel with recent Z88DK version

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#3083]
[UPDATE]: 

It seems to work with the very latest build of Z88DK from source code.
So the issue no longer exist in the latest source code.
But the latest snap versions on both branches (edge and stable) have broken parallel build support.
When will snap versions get an update?
What is also weird is that I was also getting these problems with previous snap versions on both branches.
Could snap somehow be the cause of the issue?

----------------

SYMPTOMS:
I get random compilation errors under a virtualized Linux (Lubuntu) when compiling the same code for multiple targets in parallel if a large enough number of cores are available (>4)..
I don't get these errors under Cygwin (with 16 threads/cores).
I don't get these errors under virtualized Linux in the 4-core 4-thread machine in GitHub Codespaces.
I don't get these errors under MacOS (16 core-16 thread).

[KO] under virtualized Linux I am using the latest snap edge version: `v24825-a996c99f3d-20260529`

[OK] under MacOS I have `v24132-66ef9f6c8a-20251202`

[OK] under Cygwin I have `v25337-30e751540e-20260806`

[OK] Inside the 4-core virtual Linux machine in GitHub Codespaces I have: `v1-41c54f43-20251217`

In my Cross-Lib framework, this can be reproduced by running (possibly a few times): `xl test z88dk_alt` under Linux.

The corresponding Makefile is here:
```
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/makefiles.other/chase/tests/Makefile.z88dk_quick_tests
```

It is weird because it works fine under cygwin with very recent z88dk from 20260806 and it works fine under MacOs and Linux in Codespaces with much older z88dk versions from 2025/12. It just fails with a semi-recent version from 20260529. Was the parallel build broken in May? and fixed again? 

The error may vary.
I may get 
1. a core dump or 
2. an error about appmake not being called correctly or 
3. Syntax error: Unterminated quoted string
4. an error about a missing file...
etc.
For example I get `games/chase/split_files/level.c:273:35: fatal error: Unknown symbol: HORIZONTAL_BRICK_IMAGE`
```
fabrizioc@fabrizio-virtualbox:~/Retro/CROSS-LIB/src$ xl test z88dk_alt                                                                                                                                                                
...
gmake -j 6 GNU_MAKE=gmake z88dk_quick_test -f makefiles.other/chase/tests/Makefile.z88dk_quick_tests                                                                                                                                  
Makefile_common:1743: warning: overriding recipe for target 'msx2_mode7'
Makefile_common:1712: warning: ignoring old recipe for target 'msx2_mode7'
games/chase/makefiles/Makefile.override:3: warning: overriding recipe for target 'creativision'
Makefile_common:716: warning: ignoring old recipe for target 'creativision'
games/chase/makefiles/Makefile.override:20: warning: overriding recipe for target 'gamate'
Makefile_common:645: warning: ignoring old recipe for target 'gamate'
games/chase/makefiles/Makefile.override:33: warning: overriding recipe for target 'vic20_exp_3k'
Makefile_common:876: warning: ignoring old recipe for target 'vic20_exp_3k'
games/chase/makefiles/Makefile.override:59: warning: overriding recipe for target 'vic20_exp_8k'
Makefile_common:859: warning: ignoring old recipe for target 'vic20_exp_8k'
games/chase/makefiles/Makefile.override:120: warning: overriding recipe for target 'vic20_unexpanded'
Makefile_common:915: warning: ignoring old recipe for target 'vic20_unexpanded'
games/chase/makefiles/Makefile.override:167: warning: overriding recipe for target 'c16_16k'
Makefile_common:477: warning: ignoring old recipe for target 'c16_16k'
zcc +abc80 -lm -subtype=hex -zorg=49200 \
-D__ABC80__ -clib=ansi -vn  \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-create-app -o abc80t.bin \
 \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
zcc +ace \
-D__ACE__ \
 \
-D__CONIO_GRAPHICS \
-clib=default -o acet.bin \
-D__NO_INIT_GRAPHICS \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-Cz--audio -create-app \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
zcc +aquarius -clib=ansi -vn \
 -D__AQUARIUS__  -DTINY_GAME \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
 \
-o TEST_aquarius -create-app \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
zcc +c128 \
 -subtype=disk \
-D__C128_Z80__ -DXSize=40 \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c \
-create-app -o ../build/TEST_c128.bin
zcc +cpc \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-D__CPC____ \
-D_XL_NO_SLEEP -D__NO_WAIT \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
cross_lib/sound/z88dk/psg/ay-3-8910_psg_sounds.c \
-create-app -o../build/TEST_cpc.prg \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
zcc +cpm \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-D__CPM_80X24__ \
-D_XL_NO_SLEEP -D__NO_WAIT \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-create-app -o../build/TEST_cpm.bin \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
rm -rf abc80t.bin
mv abc80t.ihx ../build/TEST_abc80.ihx 
zcc +trs80 \
-D__EG2K__ \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-subtype=eg2000disk \
 \
-lm \
-D__TRS80__ \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-create-app -o eg2kt.bin \
-D__VT52 \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
cp acet.wav ../build/TEST_ace_exp_16k.wav
rm -rf ../build/TEST_c128
rm TEST_aquarius
rm acet.wav
rm -rf ../build/TEST_c128.ldr
mv TEST_aquarius.caq ../build
rm acet.tap
rm -rf ../build/test_c128
mv _TEST_aquarius.caq ../build
rm acet.bin
rm -rf ../build/test_c128.ldr
zcc +cpm -leinstein  \
-D__EINSTEIN__ \
-D__INCLUDE_CONIO_H \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-clib=ansi \
-create-app -o../build/TEST_einstein.bin \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c 
zcc +gal \
-pragma-need=ansiterminal \
-D__GAL__ \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-vn  -create-app -o  ../build/TEST_galaksija.prg \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c 
zcc +kc -subtype=tap \
-D__KC__ \
-D__NO_INIT_GRAPHICS \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
 \
-D__VT52 \
-D__CONIO_GRAPHICS \
-D_XL_NO_SLEEP \
-D__NO_WAIT \
 \
-create-app -o../build/TEST_kc_sprites.bin \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c games/chase/generated_assets/z88dk_xchase.asm 
rm ../build/TEST_cpm.bin
zcc +lambda \
-vn -D__LAMBDA__ \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
 -create-app -o  ../build/TEST_lambda.prg \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
rm -rf ../build/TEST_cpc.cpc
zcc +m5 \
-D__CONIO_GRAPHICS \
-D__NO_INIT_GRAPHICS \
-lm -create-app -Cz--audio -subtype=tape \
-D__M5__ \
-clib=ansi -pragma-define:ansicolumns=32 \
-O0 -D_DEFAULT_ASCII -DTINY_GAME -DLESS_TEXT -D_XL_NO_SLEEP -DNO_CHASE -DNO_GAME_COMPLETED -DNO_INITIAL_SCREEN -D__NO_SCREEN_COLOR_INIT -DNO_DEAD_GHOSTS -DNO_RANDOM_LEVEL -DFLAT_ENEMIES -DGHOSTS_NUMBER=8 -DNO_STATS -DNO_WALL -lndos -Icross_lib -Icross_lib/sleep -Icross_lib/display -Icross_lib/display/graphics_mode -Icross_lib/display/alt_print -Icross_lib/include -Icross_lib/sound -Icross_lib/sound/cc65/atmos -Icross_lib/sound/cc65/c264 -Icross_lib/sound/cc65/pokey -Icross_lib/sound/cc65/sid -Icross_lib/sound/cc65/vic20 -Icross_lib/sound/cc65/gamate -Icross_lib/sound/cc65/creativision -Icross_lib/sound/cc65/atari_lynx -Icross_lib/sound/cc65/atari7800 -Icross_lib/sound/cc65/pet -Icross_lib/sound/cc65/supervision -Icross_lib/sound/cc65/cx16 -Icross_lib/sound/z88dk/bit_bang -Icross_lib/sound/z88dk/gb -Icross_lib/sound/z88dk/psg -Icross_lib/sound/lcc1802/comx -Icross_lib/sound/cmoc/mo5 -Icross_lib/sound/generic -Icross_lib/sound/gcc4ti99 -Icross_lib/sound/vbcc/bbc -Icross_lib/sound/ack/msdos86 -Icross_lib/text -Icross_lib/input -Icross_lib/rand -Icross_lib/display/redefine_characters -Icross_lib/display/tiles -Icross_lib/display/init_graphics/vbcc/bbc -Igames/chase/generated_assets -Igames/chase \
-o../build/TEST_m5.bin \
cross_lib/display/display_macros.c cross_lib/input/input_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c
games/chase/split_files/level.c:273:35: fatal error: Unknown symbol: HORIZONTAL_BRICK_IMAGE
Compilation aborted
gmake: *** [makefiles.other/chase/tests/Makefile.z88dk_quick_tests:238: kc_quick_test] Error 1
gmake: *** Waiting for unfinished jobs....
rm ../build/TEST_lambda.prg
mv eg2kt.cmd ../build/TEST_eg2k.cmd
rm ../build/TEST_galaksija.prg
rm ../build/TEST_einstein.bin
rm eg2kt.bin
rm ../build/TEST_galaksija.wav
rm ../build/TEST_m5.bin 
rm ../build/TEST_m5.cas

```

**Comment by suborb** [comment]
I've just looked at the tmp file handling inside zcc and it looks a little irregular. Given that it's a weird range of symptoms that's my guess at the moment. 

Let me get through what I'm currently working on and I'll take a look.

**Comment by Fabrizio-Caruso** [comment]
@suborb The problem is only present in the versions produced by snap. The versions are from very different dates.
Is it possible that snap is corrupting something?

**Comment by suborb** [comment]
I poked through a new snap build - probably worth giving that a go.
