### ISSUE TITLE
feature request: pass ZCCFG & PATH as command argument in zcc

### ISSUE THREAD

**Issue by RodrigoDornelles** [z88dk/z88dk#2226]
I'm working on a project, which, in the absence or preference of the programmer, downloads the compiler in a `vendor/` folder, it would be interesting if, instead of just using environment variables, it could be passed as flags.

### example 

```
zcc --cfgpath=/path/to/cfg --binpath=/path/to/bin +zx -vn test.c -o test.bin -lndos
```

another detail is that it is possible to pass the absolute path of the cfg, but it is not very useful if the inclusion of `.inc` in `.cfg` is not relative, it would be interesting to support the absence of a `/` (root) like relative path, and in the presence an absolute path.

### actual problem 

```
zcc +/path/to/cfg/zx -vn test.c -o test.bin -lndos
```

#### error 
```Can't open config file /alias.inc```

#### workaround
```
ZCCCFG=/path/to/cfg zcc +zx -vn test.c -o test.bin -lndos
```

**Comment by suborb** [comment]
I'm tinkering with extracting the dirname of the zcc command and deriving the various directories from that which I think will be a neater way than specifying the directories explicitly.

**Comment by suborb** [comment]
If invoked with a path, zcc will now launch binaries with that path and derive ZCCCFG from it. 

So, I think what you were hoping to achieve has been done.

**Comment by RodrigoDornelles** [comment]
@suborb I was having trouble understanding what was modified, can you tell me a small command example (of what changed)?

**Comment by suborb** [comment]
If you launch with /path/to/zcc then ZCCCFG will be set to /path/to/../lib/config and binaries will be invoked with /path/to/binary

Thus there should be no need to add to the path or define an environment variable.

**Comment by feilipu** [comment]
My clone of z88dk/master now won't build on Ubuntu 22.04, because it can't find [`BINDIR`](https://github.com/z88dk/z88dk/blob/master/src/zcc/zcc.c#L919), even though the definition of `BINDIR` was pulled in too.

```sh
ccache gcc -c -o zcc.o -g -O2 -DLOCAL_REGEXP -Wall -pedantic -g -MMD -I. -I../copt -I../common -I../../ext/uthash/src zcc.c
zcc.c: In function ‘main’:
zcc.c:919:41: error: ‘BINDIR’ undeclared (first use in this function)
  919 |     if ( strcmp(ptr,".") && strcmp(ptr, BINDIR)) {
      |                                         ^~~~~~
zcc.c:919:41: note: each undeclared identifier is reported only once for each function it appears in
```

Trying to fix it by doing this,

```
ccache -C
```
but that's not helping.

Is this just me?

**Comment by feilipu** [comment]
Added a `src/config.h` clean to the `Makefile` with https://github.com/z88dk/z88dk/commit/7b221027ea05a8ed7f2608aa465c5d7fb4333578

Please adjust if it is not cross-platform enough. :smile:
